# Generated by Django 4.2.11 on 2026-02-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('return_policy', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
