# Generated by Django 4.2.11 on 2026-07-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_brand_alter_product_category'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebatch',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AlterField(
            model_name='purchasebatch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted'), ('DISPOSED', 'Disposed'), ('PENDING_EXPIRY', 'Pending Expiry')], default='ACTIVE', max_length=20),
        ),
    ]
