# Generated by Django 4.2.11 on 2026-02-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('quantity_returned', models.IntegerField()),
                ('return_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_reason', models.CharField(blank=True, choices=[('EXPIRY', 'Expiry'), ('DAMAGE', 'Damage'), ('WRONG_ITEM', 'Wrong Item')], max_length=20)),
                ('recovery_type', models.CharField(blank=True, choices=[('CREDIT_NOTE', 'Credit Note'), ('REPLACEMENT', 'Replacement'), ('CASH', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.PROTECT, to='purchases.purchasebatch')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
                ('supplier', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'supplier_return',
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE_SYNC', 'Sale Sync'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('INITIAL_IMPORT', 'Initial Import')], max_length=20)),
                ('source', models.CharField(max_length=30)),
                ('quantity_change', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchasebatch')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'stock_ledger',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('adjustment_date', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, db_column='adjusted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
                ('batch', models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchasebatch')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'stock_adjustment',
            },
        ),
        migrations.CreateModel(
            name='ReorderRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField()),
                ('avg_daily_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_of_stock', models.IntegerField()),
                ('safety_stock', models.IntegerField()),
                ('suggested_quantity', models.IntegerField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('urgency', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('NORMAL', 'Normal')], max_length=10)),
                ('calculation_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'Ordered'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20)),
                ('actioned_by', models.ForeignKey(blank=True, db_column='actioned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('supplier', models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'reorder_recommendation',
            },
        ),
        migrations.CreateModel(
            name='ProductLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('GROWING', 'Growing'), ('STABLE', 'Stable'), ('DECLINING', 'Declining'), ('SLOW_MOVING', 'Slow Moving')], max_length=20)),
                ('sales_velocity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comparison_period', models.CharField(max_length=10)),
                ('recommendation', models.CharField(choices=[('RETAIN', 'Retain'), ('DISCOUNT', 'Discount'), ('DISCONTINUE', 'Discontinue'), ('MONITOR', 'Monitor')], max_length=15)),
                ('calculated_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'product_lifecycle',
            },
        ),
        migrations.CreateModel(
            name='LossRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_type', models.CharField(choices=[('EXPIRY', 'Expiry'), ('SLOW_MOVING', 'Slow Moving'), ('DAMAGE', 'Damage'), ('OTHER', 'Other')], max_length=20)),
                ('loss_quantity', models.IntegerField()),
                ('loss_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loss_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchasebatch')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
            ],
            options={
                'db_table': 'loss_record',
            },
        ),
        migrations.CreateModel(
            name='InventoryHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margin_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiry_risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_duration_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WATCH', 'Watch'), ('AT RISK', 'At Risk'), ('CRITICAL', 'Critical')], max_length=20)),
                ('recommended_action', models.CharField(blank=True, max_length=255)),
                ('rating_sufficient', models.BooleanField(default=False)),
                ('weighting_mode', models.CharField(choices=[('4-COMPONENT', '4 Component'), ('5-COMPONENT', '5 Component')], default='4-COMPONENT', max_length=15)),
                ('calculated_date', models.DateField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(blank=True, db_column='calculated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'inventory_health_score',
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_from_expiry_min', models.IntegerField()),
                ('days_from_expiry_max', models.IntegerField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_margin_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
            ],
            options={
                'db_table': 'discount_rule',
            },
        ),
        migrations.CreateModel(
            name='DiscountRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_until_expiry', models.IntegerField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_discount_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_protected', models.BooleanField(default=False)),
                ('recovery_sell', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recovery_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recovery_discard', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('best_action', models.CharField(choices=[('DISCOUNT', 'Discount'), ('RETURN', 'Return'), ('DISCARD', 'Discard')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('IGNORED', 'Ignored'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('calculated_date', models.DateField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.PROTECT, to='purchases.purchasebatch')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_discounts', to='users.appuser')),
            ],
            options={
                'db_table': 'discount_recommendation',
            },
        ),
        migrations.CreateModel(
            name='CategoryHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_health_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('healthy_count', models.IntegerField(default=0)),
                ('watch_count', models.IntegerField(default=0)),
                ('at_risk_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WATCH', 'Watch'), ('AT RISK', 'At Risk'), ('CRITICAL', 'Critical')], max_length=20)),
                ('calculated_date', models.DateField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(blank=True, db_column='calculated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'category_health_score',
            },
        ),
    ]
