# Generated by Django 4.2.11 on 2026-04-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_lifecycle_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productlifecycle',
            name='unique_product_lifecycle_period',
        ),
    ]
