# Generated by Django 4.2.11 on 2026-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_productlifecycle_unique_product_lifecycle_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reorderrecommendation',
            name='calculation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reorderrecommendation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'Ordered'), ('IGNORED', 'Ignored'), ('AUTO_RESOLVED', 'Auto Resolved')], default='PENDING', max_length=20),
        ),
    ]
