# Generated by Django 4.2.11 on 2026-08-22 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_reorderrecommendation_calculation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryhealthscore',
            name='calculated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='inventoryhealthscore',
            name='calculated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
