# Generated by Django 4.2.11 on 2026-08-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_categoryhealthscore_calculated_at_and_more'),
        ('inventory', '0005_repoint_appuser_fields'),
    ]

    operations = [
    ]
