# Generated by Django 4.2.11 on 2026-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_merge_20260827_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlifecycle',
            name='recommendation',
            field=models.CharField(choices=[('RETAIN', 'Retain'), ('DISCOUNT', 'Discount'), ('CLEARANCE', 'Clearance'), ('PHASE_OUT', 'Consider Discontinuing'), ('DISCONTINUE', 'Discontinue'), ('MONITOR', 'Monitor')], max_length=15),
        ),
    ]
