# Generated by Django 4.2.11 on 2026-09-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productlifecycle_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlifecycle',
            name='recommendation',
            field=models.CharField(choices=[('RETAIN', 'Retain'), ('DISCOUNT', 'Discount'), ('CLEARANCE', 'Clearance'), ('PHASE_OUT', 'Consider Discontinuing'), ('DISCONTINUE', 'Discontinue'), ('MONITOR', 'Monitor'), ('REVIEW_DISCOUNT', 'Review Discount'), ('DISCOUNT_REVIEW', 'Discount Review'), ('IMMEDIATE_ACTION', 'Immediate Action')], max_length=20),
        ),
    ]
