# Generated by Django 4.2.11 on 2026-02-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('password_hash', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=20, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time_slot', models.CharField(blank=True, max_length=15)),
                ('collection_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.CharField(blank=True, max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='confirmed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, to='orders.customer')),
            ],
            options={
                'db_table': 'online_order',
            },
        ),
        migrations.CreateModel(
            name='ProductRatingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('verified_count', models.IntegerField(default=0)),
                ('trend', models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DECLINING', 'Declining')], default='STABLE', max_length=15)),
                ('calculated_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'product_rating_summary',
            },
        ),
        migrations.CreateModel(
            name='OnlineOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_reserved', models.BooleanField(default=False)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='orders.onlineorder')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'online_order_item',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('reference_table', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customer')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='ChatbotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent_detected', models.CharField(choices=[('BUDGET_QUERY', 'Budget Query'), ('BRAND_QUERY', 'Brand Query'), ('PRICE_QUERY', 'Price Query'), ('AVAILABILITY_QUERY', 'Availability Query'), ('PACK_SIZE_QUERY', 'Pack Size Query'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('query_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customer')),
            ],
            options={
                'db_table': 'chatbot_log',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback_text', models.CharField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.onlineorder')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'product_rating',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
