# Generated by Django 6.0.5 on 2026-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='pickup_time_slot',
            field=models.CharField(max_length=15),
        ),
    ]
