# Generated by Django 4.2.11 on 2026-07-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='pickup_time_slot',
            field=models.CharField(max_length=15),
        ),
    ]
