# Generated by Django 6.0.2 on 2026-09-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_notificationread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotlog',
            name='intent_detected',
            field=models.CharField(choices=[('BUDGET_QUERY', 'Budget Query'), ('BRAND_QUERY', 'Brand Query'), ('PRICE_QUERY', 'Price Query'), ('AVAILABILITY_QUERY', 'Availability Query'), ('EXPIRY_QUERY', 'Expiry Query'), ('PACK_SIZE_QUERY', 'Pack Size Query'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30),
        ),
    ]
