# Generated by Django 4.2.11 on 2026-09-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_chatbot_agent_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_key', models.CharField(max_length=100, unique=True)),
                ('window_started_at', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'chatbot_rate_limit',
            },
        ),
    ]
