# Generated by Django 4.2.11 on 2026-09-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_chatbot_rate_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotlog',
            name='intent_detected',
            field=models.CharField(choices=[('AGENT_QUERY', 'Agent Query'), ('BUDGET_QUERY', 'Budget Query'), ('BRAND_QUERY', 'Brand Query'), ('PRICE_QUERY', 'Price Query'), ('AVAILABILITY_QUERY', 'Availability Query'), ('EXPIRY_QUERY', 'Expiry Query'), ('PACK_SIZE_QUERY', 'Pack Size Query'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30),
        ),
    ]
