# Generated by Django 4.2.11 on 2026-09-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_chatbotlog_intent_detected'),
        ('orders', '0007_add_expiry_query_intent'),
    ]

    operations = [
    ]
