# Generated by Django 4.2.11 on 2026-10-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_chatbotlog_intent_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
