# Generated by Django 4.2.11 on 2026-02-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=150)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_type', models.CharField(choices=[('ITEM_SALES', 'Item Sales Excel'), ('DAILY_BILLS', 'Daily Bills PDF'), ('ITEM_MASTER', 'Item Master Excel'), ('EXPORT', 'Report Export')], max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('uploaded_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'upload_log',
            },
        ),
        migrations.CreateModel(
            name='ItemSalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('quantity_sold', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('upload', models.ForeignKey(blank=True, db_column='upload_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.uploadlog')),
            ],
            options={
                'db_table': 'item_sales_record',
            },
        ),
        migrations.CreateModel(
            name='DailyBillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('bill_no', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('CARD', 'Card')], max_length=10)),
                ('is_flagged', models.BooleanField(default=False)),
                ('upload', models.ForeignKey(blank=True, db_column='upload_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.uploadlog')),
            ],
            options={
                'db_table': 'daily_bill_summary',
            },
        ),
    ]
