# Generated by Django 4.2.11 on 2026-03-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
