# Generated by Django 4.2.11 on 2026-04-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_item_sales_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemsalesrecord',
            name='item_sales_product_date_idx',
        ),
    ]
