# Generated by Django 4.2.11 on 2026-06-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_itemsalesrecord_item_sales_product_date_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(choices=[('ITEM_SALES', 'Item Sales Excel'), ('DAILY_BILLS', 'Daily Bills PDF'), ('ITEM_MASTER', 'Item Master Excel')], max_length=30)),
                ('file_name', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('bills_processed', models.IntegerField(default=0)),
                ('records_inserted', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_detail', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed')], max_length=20)),
                ('resume_point_after', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sync_log',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='dailybillsummary',
            name='is_full_discount',
            field=models.BooleanField(default=False),
        ),
    ]
