# Generated by Django 4.2.11 on 2026-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_dailybillsummary_id_alter_itemsalesrecord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlog',
            name='upload_type',
            field=models.CharField(choices=[('ITEM_SALES', 'Item Sales Excel'), ('DAILY_BILLS', 'Daily Bills PDF'), ('ITEM_MASTER', 'Item Master Excel'), ('EXPORT', 'Report Export'), ('SUPPLIER_INVOICE', 'Supplier Invoice PDF')], max_length=30),
        ),
    ]
