# Generated by Django 4.2.11 on 2026-09-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_uploadlog_upload_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlog',
            name='upload_type',
            field=models.CharField(choices=[('ITEM_SALES', 'Item Sales Excel'), ('DAILY_BILLS', 'Daily Bills PDF'), ('ITEM_MASTER', 'Item Master Excel'), ('EXPORT', 'Report Export'), ('SUPPLIER_INVOICE', 'Supplier Invoice PDF'), ('SUPPLIER_RETURN', 'Supplier Return PDF')], max_length=30),
        ),
    ]
