# Generated by Django 4.2.11 on 2026-02-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('sku_code', models.CharField(max_length=50, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reorder_threshold', models.IntegerField(default=0)),
                ('introduced_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='StoreZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('traffic_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
            ],
            options={
                'db_table': 'store_zone',
            },
        ),
        migrations.CreateModel(
            name='ZoneRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommendation_date', models.DateField(auto_now_add=True)),
                ('current_zone', models.ForeignKey(db_column='current_zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='current_recommendations', to='products.storezone')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('suggested_zone', models.ForeignKey(db_column='suggested_zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='suggested_recommendations', to='products.storezone')),
            ],
            options={
                'db_table': 'zone_recommendation',
            },
        ),
        migrations.CreateModel(
            name='ProductZoneOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, to='products.storezone')),
            ],
            options={
                'db_table': 'product_zone_override',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='default_zone',
            field=models.ForeignKey(blank=True, db_column='default_zone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.storezone'),
        ),
    ]
