# Generated by Django 4.2.11 on 2026-09-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_storezone_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonerecommendation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied')], default='PENDING', max_length=10),
        ),
    ]
