# Generated by Django 4.2.11 on 2026-09-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_zonerecommendation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneCalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('products_evaluated', models.IntegerField(default=0)),
                ('recommendations_created', models.IntegerField(default=0)),
                ('skipped_no_health_score', models.IntegerField(default=0)),
                ('skipped_no_current_zone', models.IntegerField(default=0)),
                ('skipped_duplicate', models.IntegerField(default=0)),
                ('categories_unmapped_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'zone_calculation_run',
                'ordering': ['-run_at'],
            },
        ),
    ]
