# Generated by Django 4.2.11 on 2026-09-12 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_zonerecommendation_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='productzoneoverride',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='productzoneoverride',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
